name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ Auth-with-static-user ]
  pull_request:
    branches: [ Auth-with-static-user ]
permissions:
  contents: write
  pages: write
  id-token: write

run-name: ${{ github.actor }} run playwright tests 🚀🚀🚀

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  deploy:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Checkout the repository
      with:
        fetch-depth: 0  # Ensure the full repo is checked out
    - name: Download Playwright report artifact
      uses: actions/download-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/
    - name: Check contents of playwright-report
      run: ls -R playwright-report/
    - name: Deploy Playwright report to gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub Actions token
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git checkout -B gh-pages  # Create or switch to gh-pages branch
        rm -rf *  # Remove existing contents from the branch
        cp -r ./playwright-report/* .  # Copy the report contents to the root
        git add .
        git commit -m "Deploy Playwright report to GitHub Pages"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages --force  # Force push to gh-pages
